# Generated by Django 4.0.4 on 2022-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiwonGongo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jiwon_company', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jiwon_gongo',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='jiwon_company',
            field=models.ManyToManyField(to='user.jiwongongo'),
        ),
    ]
